### PR TITLE
feature/BLB-91-replace-player-sprite-and-animation

### PR DESCRIPTION
**Pull request by xcrowy**
Replaced old Dog sprite with new Blob Ross temporary sprite, also replaced the animations for the player as well. Please check Sample_Player_Movement scene.

### CODE REVIEW

**Comment by ashabid03** [comment]
@xcrowy I'm going to scale blob a bit bigger just because he's too small in the game view. I'm editing his box collider so that it accuratly fits around him. 

Also disabled the playerInput gizmo in scene view: 
Screen Shot 2022-10-02 at 8 41 18 PM

**Comment by xcrowy** [comment]
> @xcrowy I'm going to scale blob a bit bigger just because he's too small in the game view. I'm editing his box collider so that it accuratly fits around him.
> 
> Also disabled the playerInput gizmo in scene view: Screen Shot 2022-10-02 at 8 41 18 PM

what does playerInput gizmo in scene view do ?

**Comment by ashabid03** [comment]
Getting rid of that:

Screen Shot 2022-10-02 at 8 45 38 PM

**Comment by xcrowy** [comment]
> @xcrowy I'm going to scale blob a bit bigger just because he's too small in the game view. I'm editing his box collider so that it accuratly fits around him.
> 
> Also disabled the playerInput gizmo in scene view: Screen Shot 2022-10-02 at 8 41 18 PM

also if you scale the blob in the game view, you have to scale all of the blob's sprites so that includes left, right, up and down sprite so that it can be consistent , also you dont need to change too much because these sprites are temporary, erica is still workin on it.

**Comment by ashabid03** [comment]
Scaling the gameobject won't hurt the sprites' animation. Just tested it. Also, I could some guidance on setting the collider.

**Review by ashabid03 — APPROVED** [review]

**Comment by ashabid03** [comment]
@FishError Hold off on reviewing until the empty-handed blob sprites are added.

**Comment by ashabid03** [comment]
@FishError PR can be reviewed now.

**Review by ashabid03 — APPROVED** [review]

**Review by FishError — APPROVED** [review]

**Pull request merged**
