### PR TITLE
Created boss arena placeholder

### PR DESCRIPTION
**Pull request by KaifengZhou**
Created Boss arena as specified in design doc.

Scene is currently in the placeholder folder, let me know if I should move it.

Arena is round with lava around it. (Don't ask why the lava is water)
There is a path leading into the arena, it can be used as a short cutscene where our character move into arena and then blocked off.

Arena is currently 44x44.

### CODE REVIEW

**Comment by FishError** [comment]
image

missing edge tile

**Comment by FishError** [comment]
make the tile map use composite collider and set the composite collider geometry type to polygons

**Review by xcrowy — COMMENTED** [review]
change your Edge rigidbody2d body type to static, currently if you play the game, the edge tilemaps will start falling downward

**Comment by KaifengZhou** [comment]
> image
> 
> missing edge tile

**Review by xcrowy — APPROVED** [review]

**Review by FishError — APPROVED** [review]

**Pull request merged**
