### PR TITLE
BLB-229 refactor sfx

### PR DESCRIPTION
**Pull request by xcrowy**
- Created a SFXManager that contains a singleton script that holds all SFX (in a form of a list) for all entities and contains various "Play" function for each entity. 
- SFXManager has a DontDestroyOnLoad
- This script can be referenced and used anywhere.

### CODE REVIEW

**Comment by FishError** [comment]
Just a general question. What does "based" mean in the functions? Because every time I read it I keep thinking of another meaning of based lol

**Comment by xcrowy** [comment]
> > Just a general question. What does "based" mean in the functions? Because every time I read it I keep thinking of another meaning of based lol
> 
> lol what you thinkin of? i meant "based" like "related", maybe i should change based to related?

also would it be better if instead of a list, i just stick with variable names?

**Comment by ashabid03** [comment]
> > Just a general question. What does "based" mean in the functions? Because every time I read it I keep thinking of another meaning of based lol
> 
> lol what you thinkin of? i meant "based" like "related", maybe i should change based to related?

Related sounds clearer to me.

**Comment by ashabid03** [comment]
> > > Just a general question. What does "based" mean in the functions? Because every time I read it I keep thinking of another meaning of based lol
> > 
> > 
> > lol what you thinkin of? i meant "based" like "related", maybe i should change based to related?
> 
> also would it be better if instead of a list, i just stick with variable names?

I think the list is fine

**Comment by xcrowy** [comment]
> > > > Just a general question. What does "based" mean in the functions? Because every time I read it I keep thinking of another meaning of based lol
> > > 
> > > 
> > > lol what you thinkin of? i meant "based" like "related", maybe i should change based to related?
> > 
> > 
> > also would it be better if instead of a list, i just stick with variable names?
> 
> I think the list is fine
also i tihnk we should have ash's pr in first and then mines

**Comment by ashabid03** [comment]
> > > > > Just a general question. What does "based" mean in the functions? Because every time I read it I keep thinking of another meaning of based lol
> > > > 
> > > > 
> > > > lol what you thinkin of? i meant "based" like "related", maybe i should change based to related?
> > > 
> > > 
> > > also would it be better if instead of a list, i just stick with variable names?
> > 
> > 
> > I think the list is fine
> 
> also i tihnk we should have ash's pr in first and then mines

No I think we should do your first. I think I will get the least merge conflicts. I also made some prefab changes on palette.

**Review by FishError — APPROVED** [review]

**Review by ashabid03 — APPROVED** [review]

**Pull request merged**
